layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 23
  exclude:
    #archived: true
    #forks: false
    projects:
      - alencargabriel.github.io
      - Registra-Dll
      - codemap.vscode
      - advpl-codex
      - Protheus-ORM
      - advpl-language-server
      - api-investments
      - FolhaPagamentoJAVA
      - LocadoraLocale
      - morris-php
      - tortoise-svn-for-vscode
      - wire-desktop
      - x-superobject
      

social_media:
  # behance: your_username
  facebook: G.Webmaster
  # dribbble: your_username
  linkedin: gabriel-alencar-3041b790
  stackoverflow: 8585565
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: channel/UC62XbD_xTeCBqUu4n9Lnqyg

topics:
  - name: AdvPL/TL++
    web_url: https://github.com/topics/advpl
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTy3Ei2PhLRrzaZ8hw8JMDZU1UBT9FwB7SUd-7uZp4offQgYA5g
  - name: PHP
    web_url: https://github.com/topics/PHP
    image_url: https://www.freepnglogos.com/uploads/php-logo-png/php-logo-php-elephant-logo-vectors-download-5.png
  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRl5s4XbPrxHdlWG13_BW1xr9ABhERvHjph3qp_nHKtP3uv-_MP
  - name: C# 
    web_url: https://github.com/topics/csharp
    image_url: https://upload.wikimedia.org/wikipedia/commons/8/82/C_Sharp_logo.png
  - name: VsCode
    web_url: https://github.com/topics/vscode
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/1200px-Visual_Studio_Code_1.35_icon.svg.png
  - name: SQL Server
    web_url: https://github.com/topics/sqlserver
    image_url: https://logodownload.org/wp-content/uploads/2016/10/Microsoft-SQL-Server-Logo-6.png

theme: jekyll-theme-cayman
