layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: false
    projects:
      - advpl-codex
      - advpl-language-server
      - Protheus-ORM
      - TESTE
      - LocadoraLocale
      - FolhaPagamentoJAVA

social_media:
  # behance: your_username
  facebook: G.Webmaster
  # dribbble: your_username
  linkedin: gabriel-alencar-3041b790
  stackoverflow: 8585565
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: AdvPL
    web_url: https://github.com/topics/advpl
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTy3Ei2PhLRrzaZ8hw8JMDZU1UBT9FwB7SUd-7uZp4offQgYA5g
    
theme: jekyll-theme-cayman
